import os
os.system("apt update -y")
os.system("apt upgrade -y")
os.system("N")
os.system("N")
os.system("N")
os.system("N")
os.system("N")
os.system("N")
os.system("pkg install git -y")
os.system("pkg install python -y")
os.system("pip install requests")
os.system("pip install Datetime")
os.system("python seam.py")